### ISSUE TITLE
Modify fields in dattatable edit form

### ISSUE THREAD

**Issue by rgbrinson** [gunjandatta/sp-dashboard#15]
Good afternoon Gunjan. I've got a multiselect field for materials and I need to pair down the options based upon which machine is chosen. How do I "gain control" of this field in the edit form and filter the options based on the machine choice? The machines list has a field called compatible materials that I would like to use.

**Comment by gunjandatta** [comment]
You can use the onControlRendered option to set the choice options initially. If you want to do a parent/child relationship, then you'll want to set the onChange event to call a method to set the dropdown values accordingly.

**Comment by rgbrinson** [comment]
Thanks Gunjan for the assistance!
